export const queryKeys = {
	users: "users",
	getUsersTypes: "getUsersTypes",
	generateQr: "generateQr",
	employees: "employees",
	employeeByName: "employeeByName",
	company: "company",
	suppliers: "suppliers",
	supplierByName: "supplierByName",
	departments: "departments",
	coupons: "coupons",
	couponsTypes: "couponsTypes",
	transactions: "transactions",
	administrations: "administrations",
	systemInfo: "systemInfo",
	shifts: "shifts",
	employeeReport: "employeeReport",
	bookkeepingReport: "bookkeepingReport",
	supplierReport: "supplierReport",
	hilanMonthlyReport: "hilanMonthlyReport",
	companyReport: "companyReport",
	administrationReport: "administrationReport",
};
